# Generated by Django 5.0.3 on 2024-05-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an event name', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Enter a brief description of the event', max_length=1000)),
                ('public', models.BooleanField(help_text='Make this event public or private to members')),
            ],
        ),
    ]
