# Generated by Django 5.0.3 on 2024-05-02 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this role', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='website.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
